### ISSUE TITLE
Switching to cross-compilation

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/r-ccapp-feedstock#12]
As noted in PR ( https://github.com/conda-forge/r-ccapp-feedstock/pull/11 ), Travis CI is being a bit flaky here. Jobs appear to cancel with no real info

To improve the maintenance experience, would recommend switching to cross-compilation

<hr>

Doing this would mean adding this to `conda-forge.yml`:

```yaml
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
```

Adding `cross-r-base` to `requirements/build`:

```yaml
requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
```

[Re-rendering]( https://conda-forge.org/docs/maintainer/updating_pkgs/#rerendering-feedstocks ) the feedstock to update the CI configurations accordingly
